// Generated by gencpp from file rm_msgs/GameRobotHp.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_GAMEROBOTHP_H
#define RM_MSGS_MESSAGE_GAMEROBOTHP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct GameRobotHp_
{
  typedef GameRobotHp_<ContainerAllocator> Type;

  GameRobotHp_()
    : ally_1_robot_HP(0)
    , ally_2_robot_HP(0)
    , ally_3_robot_HP(0)
    , ally_4_robot_HP(0)
    , ally_7_robot_HP(0)
    , ally_outpost_HP(0)
    , ally_base_HP(0)
    , stamp()  {
    }
  GameRobotHp_(const ContainerAllocator& _alloc)
    : ally_1_robot_HP(0)
    , ally_2_robot_HP(0)
    , ally_3_robot_HP(0)
    , ally_4_robot_HP(0)
    , ally_7_robot_HP(0)
    , ally_outpost_HP(0)
    , ally_base_HP(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint16_t _ally_1_robot_HP_type;
  _ally_1_robot_HP_type ally_1_robot_HP;

   typedef uint16_t _ally_2_robot_HP_type;
  _ally_2_robot_HP_type ally_2_robot_HP;

   typedef uint16_t _ally_3_robot_HP_type;
  _ally_3_robot_HP_type ally_3_robot_HP;

   typedef uint16_t _ally_4_robot_HP_type;
  _ally_4_robot_HP_type ally_4_robot_HP;

   typedef uint16_t _ally_7_robot_HP_type;
  _ally_7_robot_HP_type ally_7_robot_HP;

   typedef uint16_t _ally_outpost_HP_type;
  _ally_outpost_HP_type ally_outpost_HP;

   typedef uint16_t _ally_base_HP_type;
  _ally_base_HP_type ally_base_HP;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::GameRobotHp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::GameRobotHp_<ContainerAllocator> const> ConstPtr;

}; // struct GameRobotHp_

typedef ::rm_msgs::GameRobotHp_<std::allocator<void> > GameRobotHp;

typedef boost::shared_ptr< ::rm_msgs::GameRobotHp > GameRobotHpPtr;
typedef boost::shared_ptr< ::rm_msgs::GameRobotHp const> GameRobotHpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::GameRobotHp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::GameRobotHp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::GameRobotHp_<ContainerAllocator1> & lhs, const ::rm_msgs::GameRobotHp_<ContainerAllocator2> & rhs)
{
  return lhs.ally_1_robot_HP == rhs.ally_1_robot_HP &&
    lhs.ally_2_robot_HP == rhs.ally_2_robot_HP &&
    lhs.ally_3_robot_HP == rhs.ally_3_robot_HP &&
    lhs.ally_4_robot_HP == rhs.ally_4_robot_HP &&
    lhs.ally_7_robot_HP == rhs.ally_7_robot_HP &&
    lhs.ally_outpost_HP == rhs.ally_outpost_HP &&
    lhs.ally_base_HP == rhs.ally_base_HP &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::GameRobotHp_<ContainerAllocator1> & lhs, const ::rm_msgs::GameRobotHp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::GameRobotHp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::GameRobotHp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::GameRobotHp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b8c1902e96ad7c67b46c3d5637af066";
  }

  static const char* value(const ::rm_msgs::GameRobotHp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b8c1902e96ad7c6ULL;
  static const uint64_t static_value2 = 0x7b46c3d5637af066ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/GameRobotHp";
  }

  static const char* value(const ::rm_msgs::GameRobotHp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 ally_1_robot_HP\n"
"uint16 ally_2_robot_HP\n"
"uint16 ally_3_robot_HP\n"
"uint16 ally_4_robot_HP\n"
"uint16 ally_7_robot_HP\n"
"uint16 ally_outpost_HP\n"
"uint16 ally_base_HP\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::GameRobotHp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ally_1_robot_HP);
      stream.next(m.ally_2_robot_HP);
      stream.next(m.ally_3_robot_HP);
      stream.next(m.ally_4_robot_HP);
      stream.next(m.ally_7_robot_HP);
      stream.next(m.ally_outpost_HP);
      stream.next(m.ally_base_HP);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GameRobotHp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::GameRobotHp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::GameRobotHp_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ally_1_robot_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_1_robot_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ally_2_robot_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_2_robot_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ally_3_robot_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_3_robot_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ally_4_robot_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_4_robot_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ally_7_robot_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_7_robot_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ally_outpost_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_outpost_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ally_base_HP: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ally_base_HP);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_GAMEROBOTHP_H
