// Generated by gencpp from file rm_msgs/RadarRadioData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARRADIODATA_H
#define RM_MSGS_MESSAGE_RADARRADIODATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarRadioData_
{
  typedef RadarRadioData_<ContainerAllocator> Type;

  RadarRadioData_()
    : data()
    , stamp()  {
    }
  RadarRadioData_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::RadarRadioData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarRadioData_<ContainerAllocator> const> ConstPtr;

}; // struct RadarRadioData_

typedef ::rm_msgs::RadarRadioData_<std::allocator<void> > RadarRadioData;

typedef boost::shared_ptr< ::rm_msgs::RadarRadioData > RadarRadioDataPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarRadioData const> RadarRadioDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarRadioData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarRadioData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarRadioData_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarRadioData_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarRadioData_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarRadioData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarRadioData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarRadioData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarRadioData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99c47f45e705b8c5fcf00b6b60c3cc60";
  }

  static const char* value(const ::rm_msgs::RadarRadioData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99c47f45e705b8c5ULL;
  static const uint64_t static_value2 = 0xfcf00b6b60c3cc60ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarRadioData";
  }

  static const char* value(const ::rm_msgs::RadarRadioData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] data\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::RadarRadioData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarRadioData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarRadioData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarRadioData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARRADIODATA_H
