// Generated by gencpp from file rm_msgs/RadarEnemyBuff.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARENEMYBUFF_H
#define RM_MSGS_MESSAGE_RADARENEMYBUFF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rm_msgs/RadarRobotBuff.h>
#include <rm_msgs/RadarRobotBuff.h>
#include <rm_msgs/RadarRobotBuff.h>
#include <rm_msgs/RadarRobotBuff.h>
#include <rm_msgs/RadarRobotBuff.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarEnemyBuff_
{
  typedef RadarEnemyBuff_<ContainerAllocator> Type;

  RadarEnemyBuff_()
    : hero()
    , engineer()
    , standard_3()
    , standard_4()
    , sentry()
    , sentry_status(0)  {
    }
  RadarEnemyBuff_(const ContainerAllocator& _alloc)
    : hero(_alloc)
    , engineer(_alloc)
    , standard_3(_alloc)
    , standard_4(_alloc)
    , sentry(_alloc)
    , sentry_status(0)  {
  (void)_alloc;
    }



   typedef  ::rm_msgs::RadarRobotBuff_<ContainerAllocator>  _hero_type;
  _hero_type hero;

   typedef  ::rm_msgs::RadarRobotBuff_<ContainerAllocator>  _engineer_type;
  _engineer_type engineer;

   typedef  ::rm_msgs::RadarRobotBuff_<ContainerAllocator>  _standard_3_type;
  _standard_3_type standard_3;

   typedef  ::rm_msgs::RadarRobotBuff_<ContainerAllocator>  _standard_4_type;
  _standard_4_type standard_4;

   typedef  ::rm_msgs::RadarRobotBuff_<ContainerAllocator>  _sentry_type;
  _sentry_type sentry;

   typedef uint8_t _sentry_status_type;
  _sentry_status_type sentry_status;





  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> const> ConstPtr;

}; // struct RadarEnemyBuff_

typedef ::rm_msgs::RadarEnemyBuff_<std::allocator<void> > RadarEnemyBuff;

typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBuff > RadarEnemyBuffPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBuff const> RadarEnemyBuffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator2> & rhs)
{
  return lhs.hero == rhs.hero &&
    lhs.engineer == rhs.engineer &&
    lhs.standard_3 == rhs.standard_3 &&
    lhs.standard_4 == rhs.standard_4 &&
    lhs.sentry == rhs.sentry &&
    lhs.sentry_status == rhs.sentry_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9496c17234cb8fd19e6a99a196c4479b";
  }

  static const char* value(const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9496c17234cb8fd1ULL;
  static const uint64_t static_value2 = 0x9e6a99a196c4479bULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarEnemyBuff";
  }

  static const char* value(const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ID: 0x0A05 对方机器人增益\n"
"# 按照协议顺序：英雄、工程、步兵3、步兵4、哨兵\n"
"RadarRobotBuff hero\n"
"RadarRobotBuff engineer\n"
"RadarRobotBuff standard_3\n"
"RadarRobotBuff standard_4\n"
"RadarRobotBuff sentry\n"
"# 哨兵额外状态字节\n"
"uint8 sentry_status\n"
"\n"
"================================================================================\n"
"MSG: rm_msgs/RadarRobotBuff\n"
"# 单个机器人的增益信息\n"
"uint8 recovery_percent\n"
"uint16 cooling_buff\n"
"uint8 def_buff\n"
"uint8 neg_def_buff\n"
"uint16 attack_buff\n"
;
  }

  static const char* value(const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hero);
      stream.next(m.engineer);
      stream.next(m.standard_3);
      stream.next(m.standard_4);
      stream.next(m.sentry);
      stream.next(m.sentry_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarEnemyBuff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarEnemyBuff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarEnemyBuff_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hero: ";
    Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >::stream(s, indent + "  ", v.hero);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer: ";
    Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >::stream(s, indent + "  ", v.engineer);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_3: ";
    Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >::stream(s, indent + "  ", v.standard_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_4: ";
    Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >::stream(s, indent + "  ", v.standard_4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry: ";
    Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >::stream(s, indent + "  ", v.sentry);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sentry_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARENEMYBUFF_H
