// Generated by gencpp from file rm_msgs/RadarEnemyStatus.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARENEMYSTATUS_H
#define RM_MSGS_MESSAGE_RADARENEMYSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarEnemyStatus_
{
  typedef RadarEnemyStatus_<ContainerAllocator> Type;

  RadarEnemyStatus_()
    : remainder_coin(0)
    , total_coin(0)
    , status_bitmask(0)
    , enemy_assembly(false)
    , enemy_ring_highland(false)
    , enemy_trapezoidal_highland(false)
    , enemy_fort(false)
    , enemy_outpost(false)
    , enemy_flying_slope_pre(false)
    , enemy_flying_slope_post(false)
    , enemy_highway_tunnel_l(false)
    , enemy_highway_tunnel_h(false)
    , enemy_central_high(false)
    , enemy_central_low(false)
    , enemy_highway_high(false)  {
    }
  RadarEnemyStatus_(const ContainerAllocator& _alloc)
    : remainder_coin(0)
    , total_coin(0)
    , status_bitmask(0)
    , enemy_assembly(false)
    , enemy_ring_highland(false)
    , enemy_trapezoidal_highland(false)
    , enemy_fort(false)
    , enemy_outpost(false)
    , enemy_flying_slope_pre(false)
    , enemy_flying_slope_post(false)
    , enemy_highway_tunnel_l(false)
    , enemy_highway_tunnel_h(false)
    , enemy_central_high(false)
    , enemy_central_low(false)
    , enemy_highway_high(false)  {
  (void)_alloc;
    }



   typedef uint16_t _remainder_coin_type;
  _remainder_coin_type remainder_coin;

   typedef uint16_t _total_coin_type;
  _total_coin_type total_coin;

   typedef uint32_t _status_bitmask_type;
  _status_bitmask_type status_bitmask;

   typedef uint8_t _enemy_assembly_type;
  _enemy_assembly_type enemy_assembly;

   typedef uint8_t _enemy_ring_highland_type;
  _enemy_ring_highland_type enemy_ring_highland;

   typedef uint8_t _enemy_trapezoidal_highland_type;
  _enemy_trapezoidal_highland_type enemy_trapezoidal_highland;

   typedef uint8_t _enemy_fort_type;
  _enemy_fort_type enemy_fort;

   typedef uint8_t _enemy_outpost_type;
  _enemy_outpost_type enemy_outpost;

   typedef uint8_t _enemy_flying_slope_pre_type;
  _enemy_flying_slope_pre_type enemy_flying_slope_pre;

   typedef uint8_t _enemy_flying_slope_post_type;
  _enemy_flying_slope_post_type enemy_flying_slope_post;

   typedef uint8_t _enemy_highway_tunnel_l_type;
  _enemy_highway_tunnel_l_type enemy_highway_tunnel_l;

   typedef uint8_t _enemy_highway_tunnel_h_type;
  _enemy_highway_tunnel_h_type enemy_highway_tunnel_h;

   typedef uint8_t _enemy_central_high_type;
  _enemy_central_high_type enemy_central_high;

   typedef uint8_t _enemy_central_low_type;
  _enemy_central_low_type enemy_central_low;

   typedef uint8_t _enemy_highway_high_type;
  _enemy_highway_high_type enemy_highway_high;





  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RadarEnemyStatus_

typedef ::rm_msgs::RadarEnemyStatus_<std::allocator<void> > RadarEnemyStatus;

typedef boost::shared_ptr< ::rm_msgs::RadarEnemyStatus > RadarEnemyStatusPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarEnemyStatus const> RadarEnemyStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator2> & rhs)
{
  return lhs.remainder_coin == rhs.remainder_coin &&
    lhs.total_coin == rhs.total_coin &&
    lhs.status_bitmask == rhs.status_bitmask &&
    lhs.enemy_assembly == rhs.enemy_assembly &&
    lhs.enemy_ring_highland == rhs.enemy_ring_highland &&
    lhs.enemy_trapezoidal_highland == rhs.enemy_trapezoidal_highland &&
    lhs.enemy_fort == rhs.enemy_fort &&
    lhs.enemy_outpost == rhs.enemy_outpost &&
    lhs.enemy_flying_slope_pre == rhs.enemy_flying_slope_pre &&
    lhs.enemy_flying_slope_post == rhs.enemy_flying_slope_post &&
    lhs.enemy_highway_tunnel_l == rhs.enemy_highway_tunnel_l &&
    lhs.enemy_highway_tunnel_h == rhs.enemy_highway_tunnel_h &&
    lhs.enemy_central_high == rhs.enemy_central_high &&
    lhs.enemy_central_low == rhs.enemy_central_low &&
    lhs.enemy_highway_high == rhs.enemy_highway_high;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51afc1aaa64cc6b69b332c25df8411d0";
  }

  static const char* value(const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51afc1aaa64cc6b6ULL;
  static const uint64_t static_value2 = 0x9b332c25df8411d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarEnemyStatus";
  }

  static const char* value(const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 remainder_coin\n"
"uint16 total_coin\n"
"uint32 status_bitmask\n"
"\n"
"# Bit interpretation (True if occupied by enemy/active for enemy)\n"
"# Bit 0\n"
"bool enemy_assembly\n"
"# Bit 1-2\n"
"bool enemy_ring_highland\n"
"# Bit 3\n"
"bool enemy_trapezoidal_highland\n"
"# Bit 4-5\n"
"bool enemy_fort\n"
"# Bit 6-7\n"
"bool enemy_outpost\n"
"# Bit 9 (Flying Slope Pre)\n"
"bool enemy_flying_slope_pre\n"
"# Bit 10 (Flying Slope Post)\n"
"bool enemy_flying_slope_post\n"
"# Bit 11 (Highway/Tunnel L?)\n"
"bool enemy_highway_tunnel_l\n"
"# Bit 12 (Highway/Tunnel H?)\n"
"bool enemy_highway_tunnel_h\n"
"# Bit 13 (Highland High)\n"
"bool enemy_central_high\n"
"# Bit 14 (Highland Fly?)\n"
"bool enemy_central_low\n"
"# Bit 15 (Highland Road)\n"
"bool enemy_highway_high\n"
;
  }

  static const char* value(const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remainder_coin);
      stream.next(m.total_coin);
      stream.next(m.status_bitmask);
      stream.next(m.enemy_assembly);
      stream.next(m.enemy_ring_highland);
      stream.next(m.enemy_trapezoidal_highland);
      stream.next(m.enemy_fort);
      stream.next(m.enemy_outpost);
      stream.next(m.enemy_flying_slope_pre);
      stream.next(m.enemy_flying_slope_post);
      stream.next(m.enemy_highway_tunnel_l);
      stream.next(m.enemy_highway_tunnel_h);
      stream.next(m.enemy_central_high);
      stream.next(m.enemy_central_low);
      stream.next(m.enemy_highway_high);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarEnemyStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarEnemyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarEnemyStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "remainder_coin: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.remainder_coin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_coin: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.total_coin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status_bitmask: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status_bitmask);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_assembly: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_assembly);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_ring_highland: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_ring_highland);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_trapezoidal_highland: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_trapezoidal_highland);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_fort: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_fort);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_outpost: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_outpost);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_flying_slope_pre: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_flying_slope_pre);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_flying_slope_post: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_flying_slope_post);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_highway_tunnel_l: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_highway_tunnel_l);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_highway_tunnel_h: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_highway_tunnel_h);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_central_high: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_central_high);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_central_low: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_central_low);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enemy_highway_high: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_highway_high);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARENEMYSTATUS_H
