// Generated by gencpp from file rm_msgs/RadarEnemyHp.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARENEMYHP_H
#define RM_MSGS_MESSAGE_RADARENEMYHP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarEnemyHp_
{
  typedef RadarEnemyHp_<ContainerAllocator> Type;

  RadarEnemyHp_()
    : hero_hp(0)
    , engineer_hp(0)
    , standard_3_hp(0)
    , standard_4_hp(0)
    , sentry_hp(0)  {
    }
  RadarEnemyHp_(const ContainerAllocator& _alloc)
    : hero_hp(0)
    , engineer_hp(0)
    , standard_3_hp(0)
    , standard_4_hp(0)
    , sentry_hp(0)  {
  (void)_alloc;
    }



   typedef uint16_t _hero_hp_type;
  _hero_hp_type hero_hp;

   typedef uint16_t _engineer_hp_type;
  _engineer_hp_type engineer_hp;

   typedef uint16_t _standard_3_hp_type;
  _standard_3_hp_type standard_3_hp;

   typedef uint16_t _standard_4_hp_type;
  _standard_4_hp_type standard_4_hp;

   typedef uint16_t _sentry_hp_type;
  _sentry_hp_type sentry_hp;





  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> const> ConstPtr;

}; // struct RadarEnemyHp_

typedef ::rm_msgs::RadarEnemyHp_<std::allocator<void> > RadarEnemyHp;

typedef boost::shared_ptr< ::rm_msgs::RadarEnemyHp > RadarEnemyHpPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarEnemyHp const> RadarEnemyHpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarEnemyHp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarEnemyHp_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyHp_<ContainerAllocator2> & rhs)
{
  return lhs.hero_hp == rhs.hero_hp &&
    lhs.engineer_hp == rhs.engineer_hp &&
    lhs.standard_3_hp == rhs.standard_3_hp &&
    lhs.standard_4_hp == rhs.standard_4_hp &&
    lhs.sentry_hp == rhs.sentry_hp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarEnemyHp_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyHp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "237ae6302bfb5769809771e806c70a45";
  }

  static const char* value(const ::rm_msgs::RadarEnemyHp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x237ae6302bfb5769ULL;
  static const uint64_t static_value2 = 0x809771e806c70a45ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarEnemyHp";
  }

  static const char* value(const ::rm_msgs::RadarEnemyHp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ID: 0x0A02 对方机器人血量\n"
"uint16 hero_hp\n"
"uint16 engineer_hp\n"
"uint16 standard_3_hp\n"
"uint16 standard_4_hp\n"
"uint16 sentry_hp\n"
;
  }

  static const char* value(const ::rm_msgs::RadarEnemyHp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hero_hp);
      stream.next(m.engineer_hp);
      stream.next(m.standard_3_hp);
      stream.next(m.standard_4_hp);
      stream.next(m.sentry_hp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarEnemyHp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarEnemyHp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarEnemyHp_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hero_hp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hero_hp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer_hp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.engineer_hp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_3_hp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.standard_3_hp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_4_hp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.standard_4_hp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_hp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sentry_hp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARENEMYHP_H
