// Generated by gencpp from file rm_msgs/RadarEnemyPosition.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARENEMYPOSITION_H
#define RM_MSGS_MESSAGE_RADARENEMYPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarEnemyPosition_
{
  typedef RadarEnemyPosition_<ContainerAllocator> Type;

  RadarEnemyPosition_()
    : hero_x(0.0)
    , hero_y(0.0)
    , engineer_x(0.0)
    , engineer_y(0.0)
    , standard_3_x(0.0)
    , standard_3_y(0.0)
    , standard_4_x(0.0)
    , standard_4_y(0.0)
    , air_x(0.0)
    , air_y(0.0)
    , sentry_x(0.0)
    , sentry_y(0.0)  {
    }
  RadarEnemyPosition_(const ContainerAllocator& _alloc)
    : hero_x(0.0)
    , hero_y(0.0)
    , engineer_x(0.0)
    , engineer_y(0.0)
    , standard_3_x(0.0)
    , standard_3_y(0.0)
    , standard_4_x(0.0)
    , standard_4_y(0.0)
    , air_x(0.0)
    , air_y(0.0)
    , sentry_x(0.0)
    , sentry_y(0.0)  {
  (void)_alloc;
    }



   typedef float _hero_x_type;
  _hero_x_type hero_x;

   typedef float _hero_y_type;
  _hero_y_type hero_y;

   typedef float _engineer_x_type;
  _engineer_x_type engineer_x;

   typedef float _engineer_y_type;
  _engineer_y_type engineer_y;

   typedef float _standard_3_x_type;
  _standard_3_x_type standard_3_x;

   typedef float _standard_3_y_type;
  _standard_3_y_type standard_3_y;

   typedef float _standard_4_x_type;
  _standard_4_x_type standard_4_x;

   typedef float _standard_4_y_type;
  _standard_4_y_type standard_4_y;

   typedef float _air_x_type;
  _air_x_type air_x;

   typedef float _air_y_type;
  _air_y_type air_y;

   typedef float _sentry_x_type;
  _sentry_x_type sentry_x;

   typedef float _sentry_y_type;
  _sentry_y_type sentry_y;





  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> const> ConstPtr;

}; // struct RadarEnemyPosition_

typedef ::rm_msgs::RadarEnemyPosition_<std::allocator<void> > RadarEnemyPosition;

typedef boost::shared_ptr< ::rm_msgs::RadarEnemyPosition > RadarEnemyPositionPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarEnemyPosition const> RadarEnemyPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator2> & rhs)
{
  return lhs.hero_x == rhs.hero_x &&
    lhs.hero_y == rhs.hero_y &&
    lhs.engineer_x == rhs.engineer_x &&
    lhs.engineer_y == rhs.engineer_y &&
    lhs.standard_3_x == rhs.standard_3_x &&
    lhs.standard_3_y == rhs.standard_3_y &&
    lhs.standard_4_x == rhs.standard_4_x &&
    lhs.standard_4_y == rhs.standard_4_y &&
    lhs.air_x == rhs.air_x &&
    lhs.air_y == rhs.air_y &&
    lhs.sentry_x == rhs.sentry_x &&
    lhs.sentry_y == rhs.sentry_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ff9750e658ae1214e4c1775e4bd4a0c";
  }

  static const char* value(const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ff9750e658ae121ULL;
  static const uint64_t static_value2 = 0x4e4c1775e4bd4a0cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarEnemyPosition";
  }

  static const char* value(const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 hero_x\n"
"float32 hero_y\n"
"float32 engineer_x\n"
"float32 engineer_y\n"
"float32 standard_3_x\n"
"float32 standard_3_y\n"
"float32 standard_4_x\n"
"float32 standard_4_y\n"
"float32 air_x\n"
"float32 air_y\n"
"float32 sentry_x\n"
"float32 sentry_y\n"
;
  }

  static const char* value(const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hero_x);
      stream.next(m.hero_y);
      stream.next(m.engineer_x);
      stream.next(m.engineer_y);
      stream.next(m.standard_3_x);
      stream.next(m.standard_3_y);
      stream.next(m.standard_4_x);
      stream.next(m.standard_4_y);
      stream.next(m.air_x);
      stream.next(m.air_y);
      stream.next(m.sentry_x);
      stream.next(m.sentry_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarEnemyPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarEnemyPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarEnemyPosition_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hero_x: ";
    Printer<float>::stream(s, indent + "  ", v.hero_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hero_y: ";
    Printer<float>::stream(s, indent + "  ", v.hero_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer_x: ";
    Printer<float>::stream(s, indent + "  ", v.engineer_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "engineer_y: ";
    Printer<float>::stream(s, indent + "  ", v.engineer_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_3_x: ";
    Printer<float>::stream(s, indent + "  ", v.standard_3_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_3_y: ";
    Printer<float>::stream(s, indent + "  ", v.standard_3_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_4_x: ";
    Printer<float>::stream(s, indent + "  ", v.standard_4_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_4_y: ";
    Printer<float>::stream(s, indent + "  ", v.standard_4_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "air_x: ";
    Printer<float>::stream(s, indent + "  ", v.air_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "air_y: ";
    Printer<float>::stream(s, indent + "  ", v.air_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_x: ";
    Printer<float>::stream(s, indent + "  ", v.sentry_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_y: ";
    Printer<float>::stream(s, indent + "  ", v.sentry_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARENEMYPOSITION_H
