// Generated by gencpp from file rm_msgs/RadarEnemyBulletAllowance.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARENEMYBULLETALLOWANCE_H
#define RM_MSGS_MESSAGE_RADARENEMYBULLETALLOWANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarEnemyBulletAllowance_
{
  typedef RadarEnemyBulletAllowance_<ContainerAllocator> Type;

  RadarEnemyBulletAllowance_()
    : hero_bullet(0)
    , standard_3_bullet(0)
    , standard_4_bullet(0)
    , air_bullet(0)
    , sentry_bullet(0)  {
    }
  RadarEnemyBulletAllowance_(const ContainerAllocator& _alloc)
    : hero_bullet(0)
    , standard_3_bullet(0)
    , standard_4_bullet(0)
    , air_bullet(0)
    , sentry_bullet(0)  {
  (void)_alloc;
    }



   typedef uint16_t _hero_bullet_type;
  _hero_bullet_type hero_bullet;

   typedef uint16_t _standard_3_bullet_type;
  _standard_3_bullet_type standard_3_bullet;

   typedef uint16_t _standard_4_bullet_type;
  _standard_4_bullet_type standard_4_bullet;

   typedef uint16_t _air_bullet_type;
  _air_bullet_type air_bullet;

   typedef uint16_t _sentry_bullet_type;
  _sentry_bullet_type sentry_bullet;





  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> const> ConstPtr;

}; // struct RadarEnemyBulletAllowance_

typedef ::rm_msgs::RadarEnemyBulletAllowance_<std::allocator<void> > RadarEnemyBulletAllowance;

typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBulletAllowance > RadarEnemyBulletAllowancePtr;
typedef boost::shared_ptr< ::rm_msgs::RadarEnemyBulletAllowance const> RadarEnemyBulletAllowanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator2> & rhs)
{
  return lhs.hero_bullet == rhs.hero_bullet &&
    lhs.standard_3_bullet == rhs.standard_3_bullet &&
    lhs.standard_4_bullet == rhs.standard_4_bullet &&
    lhs.air_bullet == rhs.air_bullet &&
    lhs.sentry_bullet == rhs.sentry_bullet;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c381ccbc9d54f5aa402ed75f0aecc4a";
  }

  static const char* value(const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c381ccbc9d54f5aULL;
  static const uint64_t static_value2 = 0xa402ed75f0aecc4aULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarEnemyBulletAllowance";
  }

  static const char* value(const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ID: 0x0A03 对方允许发弹量\n"
"uint16 hero_bullet\n"
"uint16 standard_3_bullet\n"
"uint16 standard_4_bullet\n"
"uint16 air_bullet\n"
"uint16 sentry_bullet\n"
;
  }

  static const char* value(const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hero_bullet);
      stream.next(m.standard_3_bullet);
      stream.next(m.standard_4_bullet);
      stream.next(m.air_bullet);
      stream.next(m.sentry_bullet);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarEnemyBulletAllowance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarEnemyBulletAllowance_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hero_bullet: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hero_bullet);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_3_bullet: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.standard_3_bullet);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "standard_4_bullet: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.standard_4_bullet);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "air_bullet: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.air_bullet);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sentry_bullet: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sentry_bullet);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARENEMYBULLETALLOWANCE_H
