// Generated by gencpp from file rm_msgs/RadarCmd.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARCMD_H
#define RM_MSGS_MESSAGE_RADARCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarCmd_
{
  typedef RadarCmd_<ContainerAllocator> Type;

  RadarCmd_()
    : radar_cmd(0)
    , password_cmd(0)
    , password_1(0)
    , password_2(0)
    , password_3(0)
    , password_4(0)
    , password_5(0)
    , password_6(0)  {
    }
  RadarCmd_(const ContainerAllocator& _alloc)
    : radar_cmd(0)
    , password_cmd(0)
    , password_1(0)
    , password_2(0)
    , password_3(0)
    , password_4(0)
    , password_5(0)
    , password_6(0)  {
  (void)_alloc;
    }



   typedef uint8_t _radar_cmd_type;
  _radar_cmd_type radar_cmd;

   typedef uint8_t _password_cmd_type;
  _password_cmd_type password_cmd;

   typedef uint8_t _password_1_type;
  _password_1_type password_1;

   typedef uint8_t _password_2_type;
  _password_2_type password_2;

   typedef uint8_t _password_3_type;
  _password_3_type password_3;

   typedef uint8_t _password_4_type;
  _password_4_type password_4;

   typedef uint8_t _password_5_type;
  _password_5_type password_5;

   typedef uint8_t _password_6_type;
  _password_6_type password_6;





  typedef boost::shared_ptr< ::rm_msgs::RadarCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarCmd_<ContainerAllocator> const> ConstPtr;

}; // struct RadarCmd_

typedef ::rm_msgs::RadarCmd_<std::allocator<void> > RadarCmd;

typedef boost::shared_ptr< ::rm_msgs::RadarCmd > RadarCmdPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarCmd const> RadarCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarCmd_<ContainerAllocator2> & rhs)
{
  return lhs.radar_cmd == rhs.radar_cmd &&
    lhs.password_cmd == rhs.password_cmd &&
    lhs.password_1 == rhs.password_1 &&
    lhs.password_2 == rhs.password_2 &&
    lhs.password_3 == rhs.password_3 &&
    lhs.password_4 == rhs.password_4 &&
    lhs.password_5 == rhs.password_5 &&
    lhs.password_6 == rhs.password_6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarCmd_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b64c898bf6d85c43411778433c0cde0a";
  }

  static const char* value(const ::rm_msgs::RadarCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb64c898bf6d85c43ULL;
  static const uint64_t static_value2 = 0x411778433c0cde0aULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarCmd";
  }

  static const char* value(const ::rm_msgs::RadarCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 radar_cmd\n"
"uint8 password_cmd\n"
"uint8 password_1\n"
"uint8 password_2\n"
"uint8 password_3\n"
"uint8 password_4\n"
"uint8 password_5\n"
"uint8 password_6\n"
;
  }

  static const char* value(const ::rm_msgs::RadarCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radar_cmd);
      stream.next(m.password_cmd);
      stream.next(m.password_1);
      stream.next(m.password_2);
      stream.next(m.password_3);
      stream.next(m.password_4);
      stream.next(m.password_5);
      stream.next(m.password_6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "radar_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radar_cmd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_cmd);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_5);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "password_6: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.password_6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARCMD_H
