// Generated by gencpp from file rm_msgs/RadarDoubleKey.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARDOUBLEKEY_H
#define RM_MSGS_MESSAGE_RADARDOUBLEKEY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarDoubleKey_
{
  typedef RadarDoubleKey_<ContainerAllocator> Type;

  RadarDoubleKey_()
    : key()  {
      key.assign(0);
  }
  RadarDoubleKey_(const ContainerAllocator& _alloc)
    : key()  {
  (void)_alloc;
      key.assign(0);
  }



   typedef boost::array<uint8_t, 6>  _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> const> ConstPtr;

}; // struct RadarDoubleKey_

typedef ::rm_msgs::RadarDoubleKey_<std::allocator<void> > RadarDoubleKey;

typedef boost::shared_ptr< ::rm_msgs::RadarDoubleKey > RadarDoubleKeyPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarDoubleKey const> RadarDoubleKeyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarDoubleKey_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarDoubleKey_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarDoubleKey_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarDoubleKey_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarDoubleKey_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e7c4656cadf17b1c0d247eed3cdf8e2";
  }

  static const char* value(const ::rm_msgs::RadarDoubleKey_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e7c4656cadf17b1ULL;
  static const uint64_t static_value2 = 0xc0d247eed3cdf8e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarDoubleKey";
  }

  static const char* value(const ::rm_msgs::RadarDoubleKey_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[6] key\n"
;
  }

  static const char* value(const ::rm_msgs::RadarDoubleKey_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarDoubleKey_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarDoubleKey_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarDoubleKey_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "key: ";
    if (v.key.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.key.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.key[i]);
    }
    if (v.key.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARDOUBLEKEY_H
