// Generated by gencpp from file rm_msgs/RadarRobotBuff.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARROBOTBUFF_H
#define RM_MSGS_MESSAGE_RADARROBOTBUFF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarRobotBuff_
{
  typedef RadarRobotBuff_<ContainerAllocator> Type;

  RadarRobotBuff_()
    : recovery_percent(0)
    , cooling_buff(0)
    , def_buff(0)
    , neg_def_buff(0)
    , attack_buff(0)  {
    }
  RadarRobotBuff_(const ContainerAllocator& _alloc)
    : recovery_percent(0)
    , cooling_buff(0)
    , def_buff(0)
    , neg_def_buff(0)
    , attack_buff(0)  {
  (void)_alloc;
    }



   typedef uint8_t _recovery_percent_type;
  _recovery_percent_type recovery_percent;

   typedef uint16_t _cooling_buff_type;
  _cooling_buff_type cooling_buff;

   typedef uint8_t _def_buff_type;
  _def_buff_type def_buff;

   typedef uint8_t _neg_def_buff_type;
  _neg_def_buff_type neg_def_buff;

   typedef uint16_t _attack_buff_type;
  _attack_buff_type attack_buff;





  typedef boost::shared_ptr< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> const> ConstPtr;

}; // struct RadarRobotBuff_

typedef ::rm_msgs::RadarRobotBuff_<std::allocator<void> > RadarRobotBuff;

typedef boost::shared_ptr< ::rm_msgs::RadarRobotBuff > RadarRobotBuffPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarRobotBuff const> RadarRobotBuffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarRobotBuff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarRobotBuff_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarRobotBuff_<ContainerAllocator2> & rhs)
{
  return lhs.recovery_percent == rhs.recovery_percent &&
    lhs.cooling_buff == rhs.cooling_buff &&
    lhs.def_buff == rhs.def_buff &&
    lhs.neg_def_buff == rhs.neg_def_buff &&
    lhs.attack_buff == rhs.attack_buff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarRobotBuff_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarRobotBuff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6787d7b9505d543c4cee8752169fddfc";
  }

  static const char* value(const ::rm_msgs::RadarRobotBuff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6787d7b9505d543cULL;
  static const uint64_t static_value2 = 0x4cee8752169fddfcULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarRobotBuff";
  }

  static const char* value(const ::rm_msgs::RadarRobotBuff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 单个机器人的增益信息\n"
"uint8 recovery_percent\n"
"uint16 cooling_buff\n"
"uint8 def_buff\n"
"uint8 neg_def_buff\n"
"uint16 attack_buff\n"
;
  }

  static const char* value(const ::rm_msgs::RadarRobotBuff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recovery_percent);
      stream.next(m.cooling_buff);
      stream.next(m.def_buff);
      stream.next(m.neg_def_buff);
      stream.next(m.attack_buff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarRobotBuff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarRobotBuff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarRobotBuff_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "recovery_percent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recovery_percent);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cooling_buff: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cooling_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "def_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.def_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "neg_def_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.neg_def_buff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "attack_buff: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.attack_buff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARROBOTBUFF_H
