# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarEnemyBuff.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_msgs.msg

class RadarEnemyBuff(genpy.Message):
  _md5sum = "9496c17234cb8fd19e6a99a196c4479b"
  _type = "rm_msgs/RadarEnemyBuff"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ID: 0x0A05 对方机器人增益
# 按照协议顺序：英雄、工程、步兵3、步兵4、哨兵
RadarRobotBuff hero
RadarRobotBuff engineer
RadarRobotBuff standard_3
RadarRobotBuff standard_4
RadarRobotBuff sentry
# 哨兵额外状态字节
uint8 sentry_status

================================================================================
MSG: rm_msgs/RadarRobotBuff
# 单个机器人的增益信息
uint8 recovery_percent
uint16 cooling_buff
uint8 def_buff
uint8 neg_def_buff
uint16 attack_buff"""
  __slots__ = ['hero','engineer','standard_3','standard_4','sentry','sentry_status']
  _slot_types = ['rm_msgs/RadarRobotBuff','rm_msgs/RadarRobotBuff','rm_msgs/RadarRobotBuff','rm_msgs/RadarRobotBuff','rm_msgs/RadarRobotBuff','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hero,engineer,standard_3,standard_4,sentry,sentry_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarEnemyBuff, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hero is None:
        self.hero = rm_msgs.msg.RadarRobotBuff()
      if self.engineer is None:
        self.engineer = rm_msgs.msg.RadarRobotBuff()
      if self.standard_3 is None:
        self.standard_3 = rm_msgs.msg.RadarRobotBuff()
      if self.standard_4 is None:
        self.standard_4 = rm_msgs.msg.RadarRobotBuff()
      if self.sentry is None:
        self.sentry = rm_msgs.msg.RadarRobotBuff()
      if self.sentry_status is None:
        self.sentry_status = 0
    else:
      self.hero = rm_msgs.msg.RadarRobotBuff()
      self.engineer = rm_msgs.msg.RadarRobotBuff()
      self.standard_3 = rm_msgs.msg.RadarRobotBuff()
      self.standard_4 = rm_msgs.msg.RadarRobotBuff()
      self.sentry = rm_msgs.msg.RadarRobotBuff()
      self.sentry_status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BH2BHBH2BHBH2BHBH2BHBH2BHB().pack(_x.hero.recovery_percent, _x.hero.cooling_buff, _x.hero.def_buff, _x.hero.neg_def_buff, _x.hero.attack_buff, _x.engineer.recovery_percent, _x.engineer.cooling_buff, _x.engineer.def_buff, _x.engineer.neg_def_buff, _x.engineer.attack_buff, _x.standard_3.recovery_percent, _x.standard_3.cooling_buff, _x.standard_3.def_buff, _x.standard_3.neg_def_buff, _x.standard_3.attack_buff, _x.standard_4.recovery_percent, _x.standard_4.cooling_buff, _x.standard_4.def_buff, _x.standard_4.neg_def_buff, _x.standard_4.attack_buff, _x.sentry.recovery_percent, _x.sentry.cooling_buff, _x.sentry.def_buff, _x.sentry.neg_def_buff, _x.sentry.attack_buff, _x.sentry_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.hero is None:
        self.hero = rm_msgs.msg.RadarRobotBuff()
      if self.engineer is None:
        self.engineer = rm_msgs.msg.RadarRobotBuff()
      if self.standard_3 is None:
        self.standard_3 = rm_msgs.msg.RadarRobotBuff()
      if self.standard_4 is None:
        self.standard_4 = rm_msgs.msg.RadarRobotBuff()
      if self.sentry is None:
        self.sentry = rm_msgs.msg.RadarRobotBuff()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.hero.recovery_percent, _x.hero.cooling_buff, _x.hero.def_buff, _x.hero.neg_def_buff, _x.hero.attack_buff, _x.engineer.recovery_percent, _x.engineer.cooling_buff, _x.engineer.def_buff, _x.engineer.neg_def_buff, _x.engineer.attack_buff, _x.standard_3.recovery_percent, _x.standard_3.cooling_buff, _x.standard_3.def_buff, _x.standard_3.neg_def_buff, _x.standard_3.attack_buff, _x.standard_4.recovery_percent, _x.standard_4.cooling_buff, _x.standard_4.def_buff, _x.standard_4.neg_def_buff, _x.standard_4.attack_buff, _x.sentry.recovery_percent, _x.sentry.cooling_buff, _x.sentry.def_buff, _x.sentry.neg_def_buff, _x.sentry.attack_buff, _x.sentry_status,) = _get_struct_BH2BHBH2BHBH2BHBH2BHBH2BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BH2BHBH2BHBH2BHBH2BHBH2BHB().pack(_x.hero.recovery_percent, _x.hero.cooling_buff, _x.hero.def_buff, _x.hero.neg_def_buff, _x.hero.attack_buff, _x.engineer.recovery_percent, _x.engineer.cooling_buff, _x.engineer.def_buff, _x.engineer.neg_def_buff, _x.engineer.attack_buff, _x.standard_3.recovery_percent, _x.standard_3.cooling_buff, _x.standard_3.def_buff, _x.standard_3.neg_def_buff, _x.standard_3.attack_buff, _x.standard_4.recovery_percent, _x.standard_4.cooling_buff, _x.standard_4.def_buff, _x.standard_4.neg_def_buff, _x.standard_4.attack_buff, _x.sentry.recovery_percent, _x.sentry.cooling_buff, _x.sentry.def_buff, _x.sentry.neg_def_buff, _x.sentry.attack_buff, _x.sentry_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.hero is None:
        self.hero = rm_msgs.msg.RadarRobotBuff()
      if self.engineer is None:
        self.engineer = rm_msgs.msg.RadarRobotBuff()
      if self.standard_3 is None:
        self.standard_3 = rm_msgs.msg.RadarRobotBuff()
      if self.standard_4 is None:
        self.standard_4 = rm_msgs.msg.RadarRobotBuff()
      if self.sentry is None:
        self.sentry = rm_msgs.msg.RadarRobotBuff()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.hero.recovery_percent, _x.hero.cooling_buff, _x.hero.def_buff, _x.hero.neg_def_buff, _x.hero.attack_buff, _x.engineer.recovery_percent, _x.engineer.cooling_buff, _x.engineer.def_buff, _x.engineer.neg_def_buff, _x.engineer.attack_buff, _x.standard_3.recovery_percent, _x.standard_3.cooling_buff, _x.standard_3.def_buff, _x.standard_3.neg_def_buff, _x.standard_3.attack_buff, _x.standard_4.recovery_percent, _x.standard_4.cooling_buff, _x.standard_4.def_buff, _x.standard_4.neg_def_buff, _x.standard_4.attack_buff, _x.sentry.recovery_percent, _x.sentry.cooling_buff, _x.sentry.def_buff, _x.sentry.neg_def_buff, _x.sentry.attack_buff, _x.sentry_status,) = _get_struct_BH2BHBH2BHBH2BHBH2BHBH2BHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BH2BHBH2BHBH2BHBH2BHBH2BHB = None
def _get_struct_BH2BHBH2BHBH2BHBH2BHBH2BHB():
    global _struct_BH2BHBH2BHBH2BHBH2BHBH2BHB
    if _struct_BH2BHBH2BHBH2BHBH2BHBH2BHB is None:
        _struct_BH2BHBH2BHBH2BHBH2BHBH2BHB = struct.Struct("<BH2BHBH2BHBH2BHBH2BHBH2BHB")
    return _struct_BH2BHBH2BHBH2BHBH2BHBH2BHB
