# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarEnemyHp.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarEnemyHp(genpy.Message):
  _md5sum = "237ae6302bfb5769809771e806c70a45"
  _type = "rm_msgs/RadarEnemyHp"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ID: 0x0A02 对方机器人血量
uint16 hero_hp
uint16 engineer_hp
uint16 standard_3_hp
uint16 standard_4_hp
uint16 sentry_hp"""
  __slots__ = ['hero_hp','engineer_hp','standard_3_hp','standard_4_hp','sentry_hp']
  _slot_types = ['uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hero_hp,engineer_hp,standard_3_hp,standard_4_hp,sentry_hp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarEnemyHp, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hero_hp is None:
        self.hero_hp = 0
      if self.engineer_hp is None:
        self.engineer_hp = 0
      if self.standard_3_hp is None:
        self.standard_3_hp = 0
      if self.standard_4_hp is None:
        self.standard_4_hp = 0
      if self.sentry_hp is None:
        self.sentry_hp = 0
    else:
      self.hero_hp = 0
      self.engineer_hp = 0
      self.standard_3_hp = 0
      self.standard_4_hp = 0
      self.sentry_hp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5H().pack(_x.hero_hp, _x.engineer_hp, _x.standard_3_hp, _x.standard_4_hp, _x.sentry_hp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.hero_hp, _x.engineer_hp, _x.standard_3_hp, _x.standard_4_hp, _x.sentry_hp,) = _get_struct_5H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5H().pack(_x.hero_hp, _x.engineer_hp, _x.standard_3_hp, _x.standard_4_hp, _x.sentry_hp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.hero_hp, _x.engineer_hp, _x.standard_3_hp, _x.standard_4_hp, _x.sentry_hp,) = _get_struct_5H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5H = None
def _get_struct_5H():
    global _struct_5H
    if _struct_5H is None:
        _struct_5H = struct.Struct("<5H")
    return _struct_5H
