# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarEnemyStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarEnemyStatus(genpy.Message):
  _md5sum = "51afc1aaa64cc6b69b332c25df8411d0"
  _type = "rm_msgs/RadarEnemyStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 remainder_coin
uint16 total_coin
uint32 status_bitmask

# Bit interpretation (True if occupied by enemy/active for enemy)
# Bit 0
bool enemy_assembly
# Bit 1-2
bool enemy_ring_highland
# Bit 3
bool enemy_trapezoidal_highland
# Bit 4-5
bool enemy_fort
# Bit 6-7
bool enemy_outpost
# Bit 9 (Flying Slope Pre)
bool enemy_flying_slope_pre
# Bit 10 (Flying Slope Post)
bool enemy_flying_slope_post
# Bit 11 (Highway/Tunnel L?)
bool enemy_highway_tunnel_l
# Bit 12 (Highway/Tunnel H?)
bool enemy_highway_tunnel_h
# Bit 13 (Highland High)
bool enemy_central_high
# Bit 14 (Highland Fly?)
bool enemy_central_low
# Bit 15 (Highland Road)
bool enemy_highway_high
"""
  __slots__ = ['remainder_coin','total_coin','status_bitmask','enemy_assembly','enemy_ring_highland','enemy_trapezoidal_highland','enemy_fort','enemy_outpost','enemy_flying_slope_pre','enemy_flying_slope_post','enemy_highway_tunnel_l','enemy_highway_tunnel_h','enemy_central_high','enemy_central_low','enemy_highway_high']
  _slot_types = ['uint16','uint16','uint32','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       remainder_coin,total_coin,status_bitmask,enemy_assembly,enemy_ring_highland,enemy_trapezoidal_highland,enemy_fort,enemy_outpost,enemy_flying_slope_pre,enemy_flying_slope_post,enemy_highway_tunnel_l,enemy_highway_tunnel_h,enemy_central_high,enemy_central_low,enemy_highway_high

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarEnemyStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.remainder_coin is None:
        self.remainder_coin = 0
      if self.total_coin is None:
        self.total_coin = 0
      if self.status_bitmask is None:
        self.status_bitmask = 0
      if self.enemy_assembly is None:
        self.enemy_assembly = False
      if self.enemy_ring_highland is None:
        self.enemy_ring_highland = False
      if self.enemy_trapezoidal_highland is None:
        self.enemy_trapezoidal_highland = False
      if self.enemy_fort is None:
        self.enemy_fort = False
      if self.enemy_outpost is None:
        self.enemy_outpost = False
      if self.enemy_flying_slope_pre is None:
        self.enemy_flying_slope_pre = False
      if self.enemy_flying_slope_post is None:
        self.enemy_flying_slope_post = False
      if self.enemy_highway_tunnel_l is None:
        self.enemy_highway_tunnel_l = False
      if self.enemy_highway_tunnel_h is None:
        self.enemy_highway_tunnel_h = False
      if self.enemy_central_high is None:
        self.enemy_central_high = False
      if self.enemy_central_low is None:
        self.enemy_central_low = False
      if self.enemy_highway_high is None:
        self.enemy_highway_high = False
    else:
      self.remainder_coin = 0
      self.total_coin = 0
      self.status_bitmask = 0
      self.enemy_assembly = False
      self.enemy_ring_highland = False
      self.enemy_trapezoidal_highland = False
      self.enemy_fort = False
      self.enemy_outpost = False
      self.enemy_flying_slope_pre = False
      self.enemy_flying_slope_post = False
      self.enemy_highway_tunnel_l = False
      self.enemy_highway_tunnel_h = False
      self.enemy_central_high = False
      self.enemy_central_low = False
      self.enemy_highway_high = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2HI12B().pack(_x.remainder_coin, _x.total_coin, _x.status_bitmask, _x.enemy_assembly, _x.enemy_ring_highland, _x.enemy_trapezoidal_highland, _x.enemy_fort, _x.enemy_outpost, _x.enemy_flying_slope_pre, _x.enemy_flying_slope_post, _x.enemy_highway_tunnel_l, _x.enemy_highway_tunnel_h, _x.enemy_central_high, _x.enemy_central_low, _x.enemy_highway_high))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.remainder_coin, _x.total_coin, _x.status_bitmask, _x.enemy_assembly, _x.enemy_ring_highland, _x.enemy_trapezoidal_highland, _x.enemy_fort, _x.enemy_outpost, _x.enemy_flying_slope_pre, _x.enemy_flying_slope_post, _x.enemy_highway_tunnel_l, _x.enemy_highway_tunnel_h, _x.enemy_central_high, _x.enemy_central_low, _x.enemy_highway_high,) = _get_struct_2HI12B().unpack(str[start:end])
      self.enemy_assembly = bool(self.enemy_assembly)
      self.enemy_ring_highland = bool(self.enemy_ring_highland)
      self.enemy_trapezoidal_highland = bool(self.enemy_trapezoidal_highland)
      self.enemy_fort = bool(self.enemy_fort)
      self.enemy_outpost = bool(self.enemy_outpost)
      self.enemy_flying_slope_pre = bool(self.enemy_flying_slope_pre)
      self.enemy_flying_slope_post = bool(self.enemy_flying_slope_post)
      self.enemy_highway_tunnel_l = bool(self.enemy_highway_tunnel_l)
      self.enemy_highway_tunnel_h = bool(self.enemy_highway_tunnel_h)
      self.enemy_central_high = bool(self.enemy_central_high)
      self.enemy_central_low = bool(self.enemy_central_low)
      self.enemy_highway_high = bool(self.enemy_highway_high)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2HI12B().pack(_x.remainder_coin, _x.total_coin, _x.status_bitmask, _x.enemy_assembly, _x.enemy_ring_highland, _x.enemy_trapezoidal_highland, _x.enemy_fort, _x.enemy_outpost, _x.enemy_flying_slope_pre, _x.enemy_flying_slope_post, _x.enemy_highway_tunnel_l, _x.enemy_highway_tunnel_h, _x.enemy_central_high, _x.enemy_central_low, _x.enemy_highway_high))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.remainder_coin, _x.total_coin, _x.status_bitmask, _x.enemy_assembly, _x.enemy_ring_highland, _x.enemy_trapezoidal_highland, _x.enemy_fort, _x.enemy_outpost, _x.enemy_flying_slope_pre, _x.enemy_flying_slope_post, _x.enemy_highway_tunnel_l, _x.enemy_highway_tunnel_h, _x.enemy_central_high, _x.enemy_central_low, _x.enemy_highway_high,) = _get_struct_2HI12B().unpack(str[start:end])
      self.enemy_assembly = bool(self.enemy_assembly)
      self.enemy_ring_highland = bool(self.enemy_ring_highland)
      self.enemy_trapezoidal_highland = bool(self.enemy_trapezoidal_highland)
      self.enemy_fort = bool(self.enemy_fort)
      self.enemy_outpost = bool(self.enemy_outpost)
      self.enemy_flying_slope_pre = bool(self.enemy_flying_slope_pre)
      self.enemy_flying_slope_post = bool(self.enemy_flying_slope_post)
      self.enemy_highway_tunnel_l = bool(self.enemy_highway_tunnel_l)
      self.enemy_highway_tunnel_h = bool(self.enemy_highway_tunnel_h)
      self.enemy_central_high = bool(self.enemy_central_high)
      self.enemy_central_low = bool(self.enemy_central_low)
      self.enemy_highway_high = bool(self.enemy_highway_high)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2HI12B = None
def _get_struct_2HI12B():
    global _struct_2HI12B
    if _struct_2HI12B is None:
        _struct_2HI12B = struct.Struct("<2HI12B")
    return _struct_2HI12B
