# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarEnemyPosition.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarEnemyPosition(genpy.Message):
  _md5sum = "4ff9750e658ae1214e4c1775e4bd4a0c"
  _type = "rm_msgs/RadarEnemyPosition"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 hero_x
float32 hero_y
float32 engineer_x
float32 engineer_y
float32 standard_3_x
float32 standard_3_y
float32 standard_4_x
float32 standard_4_y
float32 air_x
float32 air_y
float32 sentry_x
float32 sentry_y
"""
  __slots__ = ['hero_x','hero_y','engineer_x','engineer_y','standard_3_x','standard_3_y','standard_4_x','standard_4_y','air_x','air_y','sentry_x','sentry_y']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hero_x,hero_y,engineer_x,engineer_y,standard_3_x,standard_3_y,standard_4_x,standard_4_y,air_x,air_y,sentry_x,sentry_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarEnemyPosition, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hero_x is None:
        self.hero_x = 0.
      if self.hero_y is None:
        self.hero_y = 0.
      if self.engineer_x is None:
        self.engineer_x = 0.
      if self.engineer_y is None:
        self.engineer_y = 0.
      if self.standard_3_x is None:
        self.standard_3_x = 0.
      if self.standard_3_y is None:
        self.standard_3_y = 0.
      if self.standard_4_x is None:
        self.standard_4_x = 0.
      if self.standard_4_y is None:
        self.standard_4_y = 0.
      if self.air_x is None:
        self.air_x = 0.
      if self.air_y is None:
        self.air_y = 0.
      if self.sentry_x is None:
        self.sentry_x = 0.
      if self.sentry_y is None:
        self.sentry_y = 0.
    else:
      self.hero_x = 0.
      self.hero_y = 0.
      self.engineer_x = 0.
      self.engineer_y = 0.
      self.standard_3_x = 0.
      self.standard_3_y = 0.
      self.standard_4_x = 0.
      self.standard_4_y = 0.
      self.air_x = 0.
      self.air_y = 0.
      self.sentry_x = 0.
      self.sentry_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12f().pack(_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.air_x, _x.air_y, _x.sentry_x, _x.sentry_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.air_x, _x.air_y, _x.sentry_x, _x.sentry_y,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12f().pack(_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.air_x, _x.air_y, _x.sentry_x, _x.sentry_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.air_x, _x.air_y, _x.sentry_x, _x.sentry_y,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12f = None
def _get_struct_12f():
    global _struct_12f
    if _struct_12f is None:
        _struct_12f = struct.Struct("<12f")
    return _struct_12f
