# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarEnemyBulletAllowance.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarEnemyBulletAllowance(genpy.Message):
  _md5sum = "9c381ccbc9d54f5aa402ed75f0aecc4a"
  _type = "rm_msgs/RadarEnemyBulletAllowance"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ID: 0x0A03 对方允许发弹量
uint16 hero_bullet
uint16 standard_3_bullet
uint16 standard_4_bullet
uint16 air_bullet
uint16 sentry_bullet
"""
  __slots__ = ['hero_bullet','standard_3_bullet','standard_4_bullet','air_bullet','sentry_bullet']
  _slot_types = ['uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hero_bullet,standard_3_bullet,standard_4_bullet,air_bullet,sentry_bullet

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarEnemyBulletAllowance, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hero_bullet is None:
        self.hero_bullet = 0
      if self.standard_3_bullet is None:
        self.standard_3_bullet = 0
      if self.standard_4_bullet is None:
        self.standard_4_bullet = 0
      if self.air_bullet is None:
        self.air_bullet = 0
      if self.sentry_bullet is None:
        self.sentry_bullet = 0
    else:
      self.hero_bullet = 0
      self.standard_3_bullet = 0
      self.standard_4_bullet = 0
      self.air_bullet = 0
      self.sentry_bullet = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5H().pack(_x.hero_bullet, _x.standard_3_bullet, _x.standard_4_bullet, _x.air_bullet, _x.sentry_bullet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.hero_bullet, _x.standard_3_bullet, _x.standard_4_bullet, _x.air_bullet, _x.sentry_bullet,) = _get_struct_5H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5H().pack(_x.hero_bullet, _x.standard_3_bullet, _x.standard_4_bullet, _x.air_bullet, _x.sentry_bullet))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.hero_bullet, _x.standard_3_bullet, _x.standard_4_bullet, _x.air_bullet, _x.sentry_bullet,) = _get_struct_5H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5H = None
def _get_struct_5H():
    global _struct_5H
    if _struct_5H is None:
        _struct_5H = struct.Struct("<5H")
    return _struct_5H
