# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarRobotBuff.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RadarRobotBuff(genpy.Message):
  _md5sum = "6787d7b9505d543c4cee8752169fddfc"
  _type = "rm_msgs/RadarRobotBuff"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 单个机器人的增益信息
uint8 recovery_percent
uint16 cooling_buff
uint8 def_buff
uint8 neg_def_buff
uint16 attack_buff"""
  __slots__ = ['recovery_percent','cooling_buff','def_buff','neg_def_buff','attack_buff']
  _slot_types = ['uint8','uint16','uint8','uint8','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       recovery_percent,cooling_buff,def_buff,neg_def_buff,attack_buff

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarRobotBuff, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.recovery_percent is None:
        self.recovery_percent = 0
      if self.cooling_buff is None:
        self.cooling_buff = 0
      if self.def_buff is None:
        self.def_buff = 0
      if self.neg_def_buff is None:
        self.neg_def_buff = 0
      if self.attack_buff is None:
        self.attack_buff = 0
    else:
      self.recovery_percent = 0
      self.cooling_buff = 0
      self.def_buff = 0
      self.neg_def_buff = 0
      self.attack_buff = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BH2BH().pack(_x.recovery_percent, _x.cooling_buff, _x.def_buff, _x.neg_def_buff, _x.attack_buff))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.recovery_percent, _x.cooling_buff, _x.def_buff, _x.neg_def_buff, _x.attack_buff,) = _get_struct_BH2BH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BH2BH().pack(_x.recovery_percent, _x.cooling_buff, _x.def_buff, _x.neg_def_buff, _x.attack_buff))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.recovery_percent, _x.cooling_buff, _x.def_buff, _x.neg_def_buff, _x.attack_buff,) = _get_struct_BH2BH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BH2BH = None
def _get_struct_BH2BH():
    global _struct_BH2BH
    if _struct_BH2BH is None:
        _struct_BH2BH = struct.Struct("<BH2BH")
    return _struct_BH2BH
